mysql:
  dsn: root:112358@tcp(127.0.0.1:3306)/tiktok_e-commence?charset=utf8mb4&parseTime=True&loc=Local
server:
  service_name: payment-server
  ip: 127.0.0.1
  port: 8006
gin:
  ip: 127.0.0.1
  port: 8086