definitions:
  common.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  model.ListProductsReq:
    properties:
      categoryName:
        type: string
      page:
        type: integer
      pageSize:
        type: integer
    type: object
  model.LoginReq:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.RegisterReq:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
paths:
  /product/list:
    post:
      consumes:
      - application/json
      parameters:
      - description: 查询的商品和分页信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.ListProductsReq'
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            $ref: '#/definitions/common.Response'
      summary: 分页查询商品api
      tags:
      - 商品服务
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录的用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/common.Response'
      summary: 登录用户api
      tags:
      - 用户服务
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 新增的用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            $ref: '#/definitions/common.Response'
      summary: 注册用户api
      tags:
      - 用户服务
swagger: "2.0"
